# Generated by Django 5.1.2 on 2024-10-15 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=255, unique=True)),
                ('short_description', models.TextField()),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.services')),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
