# Generated by Django 5.1.2 on 2024-10-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='bussiness_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
