# Generated by Django 5.1.2 on 2024-10-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='dummy.png', upload_to='media/images/'),
            preserve_default=False,
        ),
    ]
