# Generated by Django 5.1.2 on 2024-10-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_services_address1_services_address2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='address1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='address2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
