# Generated by Django 5.1.2 on 2024-10-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default='dummy.jpg', upload_to='media/services/'),
            preserve_default=False,
        ),
    ]
